### ISSUE TITLE
Arquivos JSON (remover "mistério")

### ISSUE THREAD

**Issue by kyriosdata** [tonymfreitas/medicaments-tcc-ufg#1]
- Acrescentar os arquivos JSON disponibilizados no AWS S3 no presente repositório.
- Acrescentar como os arquivos JSON foram gerados/obtidos. Entendo que a geração pode ter que fazer parte deste projeto.
- O modelo de dados é compatível com este [aqui](https://camo.githubusercontent.com/1a55d63bb4a1ec8cb5e49279406d5bfb84225feb37f99068c2d6779c0f9a87bd/687474703a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f70726f78793f63616368653d6e6f267372633d68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6b7972696f73646174612f6d65646963616d656e746f732f6d61737465722f554d4c2f6461646f732e70756d6c). Veja complemento desta atividade, ou extensão, registrada em issue específica (#2)

**Comment by tonymfreitas** [comment]
Olá professor, estarei atualizando o repositório esta semana, com as
alterações mencionadas acima e podemos revisar para verificar se é isso
mesmo.
Sobre a forma de nos reunirmos, continuará da mesma forma EAD ?
A partir de quando podemos retomar a segunda parte do TCC ?

Em qui., 14 de abr. de 2022 às 12:15, Fábio Nogueira de Lucena <
***@***.***> escreveu:

**Comment by kyriosdata** [comment]
Quando concluir, por favor feche esta issue. 

Especificamente sobre a compatibilidade dos dados, agora temos um referencial formal, adotado pelo Brasil.

**Comment by tonymfreitas** [comment]
Oi Professor , desculpe a demora para resolver as issues.

O modelo de dados foi adequado ao diagrama de arquitetura contendo basicamente 4 elementos: medicaments, classificationatc, pharmaceutitalform, availability.

O modelo de classificação ATC implementado é semelhante ao descrito neste [site](https://www.who.int/tools/atc-ddd-toolkit/atc-classification)

Conforme havíamos definido, os dados ficariam disponíveis em uma estrutura (como um bucketS3) em que os clients poderiam consumir os dados. O formado atual para consumo são dois arquivos JSON (medicaments & classification ATC) que são gerados pelo nosso backend de tempos em tempos por um scheduler job.
No repositório eu coloquei os jsons como exemplo.
